<a href="https://colab.research.google.com/github/OmarAlHajjar/Machine-Learning/blob/master/Copy_of_Step_2_3_DataSets.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
!pip install --upgrade tensorflow

Requirement already up-to-date: tensorflow in /usr/local/lib/python3.6/dist-packages (2.2.0rc2)


In [0]:
import tensorflow as tf
print(tf.__version__)

2.2.0-rc2


In [0]:
import tensorflow as tf
import numpy as np
import itertools 
import collections
dataset = tf.data.Dataset.from_tensor_slices([1, 2, 3]) # the simplest way to create a dataset is to create it from a python list:
for element in dataset: 
  print(element)

tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)


In [0]:
#dataset = tf.data.TextLineDataset(["file1.txt", "file2.txt"])  # To process lines from files, use tf.data.TextLineDataset0
dataset = tf.data.Dataset.from_tensor_slices([1, 2, 3]) 
dataset = dataset.map(lambda x: x*2) #  Once you have a dataset, you can apply transformations to prepare the data for your model:
list(dataset.as_numpy_iterator()) 

[2, 4, 6]

In [0]:
#Creates a dataset of a step-separated range of values
list(dataset.range(5).as_numpy_iterator()) 



[0, 1, 2, 3, 4]

In [0]:
list(dataset.range(2, 5).as_numpy_iterator()) 

[2, 3, 4]

In [0]:
list(dataset.range(1, 5, 2).as_numpy_iterator()) 

[1, 3]

In [0]:
list(dataset.range(1, 5, -2).as_numpy_iterator()) 

[]

In [0]:
list(dataset.range(5, 1, -2).as_numpy_iterator()) 

[5, 3]

In [0]:
list(dataset.range(5, 1).as_numpy_iterator()) 

[]

In [0]:
#Reduces the input dataset to a single element.
tf.data.Dataset.range(5).reduce(np.int64(0), lambda x, _: x + 1).numpy() 
#reduce(initial_state, reduce_func)
#Reduces the input dataset to a single element.
#The transformation calls reduce_func successively on every element 
#of the input dataset until the dataset is exhausted, 
#aggregating information in its internal state. 
#The initial_state argument is used for the initial state 
# and the final state is returned as the result.

5

In [0]:
tf.data.Dataset.range(5).reduce(np.int64(0), lambda x, y: x + y).numpy()

10

In [0]:
dataset = tf.data.Dataset.from_tensor_slices([1, 2, 3]) 
dataset = dataset.repeat(3) 
list(dataset.as_numpy_iterator()) 
#Repeats this dataset so each original value is seen count times.

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [0]:
dataset = dataset.range(1, 6)  # ==> [ 1, 2, 3, 4, 5 ] 
dataset = dataset.map(lambda x: x + 1) 
#  Maps map_func across the elements of this dataset.
list(dataset.as_numpy_iterator())

[2, 3, 4, 5, 6]

In [0]:
dataset = dataset.range(5) 
# `map_func` takes a single argument of type `tf.Tensor` with the same 
# shape and dtype. 
result = dataset.map(lambda x: x + 1) 

In [0]:
# Each element is a tuple containing two `tf.Tensor` objects. 
elements = [(1, "foo"), (2, "bar"), (3, "baz)")] 
dataset = tf.data.Dataset.from_generator( 
    lambda: elements, (tf.int32, tf.string)) 
# `map_func` takes two arguments of type `tf.Tensor`. This function 
# projects out just the first component. 
result = dataset.map(lambda x_int, y_str: x_int) 
list(result.as_numpy_iterator()) 

[1, 2, 3]

In [0]:
import tensorflow as tf
import numpy as np
import itertools 
import collections
a = 1 # Integer element 
b = 2.0 # Float element 
c = (1, 2) # Tuple element with 2 components 
d = {"a": (2, 2), "b": 3} # Dict element with 3 components 
Point = collections.namedtuple("Point", ["x", "y"]) # doctest: +SKIP Elements can be nested structures of tuples, named tuples, and dictionaries.
e = Point(1, 2) # Named tuple # doctest: +SKIP 
f = tf.data.Dataset.range(10) # Dataset element 
e                  # readable __repr__ with a name=value style

Point(x=1, y=2)

In [0]:
e[0] + e[1] # indexable like the plain tuple (1, 2)

3

In [0]:
x, y = e                # unpack like a regular tuple

In [0]:
x, y

(1, 2)

In [0]:
e.x + e.y               # fields also accessible by name

3

In [0]:
dataset = tf.data.Dataset.from_tensor_slices([1, 2, 3]).element_spec  # element_spec: The type specification of an element of this dataset.

In [0]:
dataset = tf.data.Dataset.range(100) 
def dataset_fn(ds): # transformation_func: A function that takes one Dataset argument and returns a Dataset.
  return ds.filter(lambda x: x < 5) 
dataset = dataset.apply(dataset_fn) # apply enables chaining of custom Dataset transformations, which are represented as functions that take one Dataset argument and return a transformed Dataset.
list(dataset.as_numpy_iterator()) # Returns an iterator which converts all elements of the dataset to numpy.

[0, 1, 2, 3, 4]

In [0]:
dataset = tf.data.Dataset.from_tensor_slices([1, 2, 3]) 
for element in dataset.as_numpy_iterator(): 
  print(element)

1
2
3


In [0]:
dataset = tf.data.Dataset.from_tensor_slices([1, 2, 3]) 
print(list(dataset.as_numpy_iterator())) 

[1, 2, 3]


In [0]:
dataset = tf.data.Dataset.from_tensor_slices({'a': ([1, 2], [3, 4]), 
                                              'b': [5, 6]}) 
list(dataset.as_numpy_iterator()) == [{'a': (1, 3), 'b': 5}, # as_numpy_iterator() will preserve the nested structure of dataset elements.
                                      {'a': (2, 4), 'b': 6}] 

True

In [0]:
dataset = tf.data.Dataset.range(8)  
dataset = dataset.batch(3) # Combines consecutive elements of this dataset into batches.
list(dataset.as_numpy_iterator()) 

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7])]

In [0]:
dataset = tf.data.Dataset.range(8) 
dataset = dataset.batch(3, drop_remainder=True) #  If your program depends on the batches having the same outer dimension, you should set the drop_remainder argument to True to prevent the smaller batch from being produced.
list(dataset.as_numpy_iterator()) 

[array([0, 1, 2]), array([3, 4, 5])]

In [0]:
dataset = tf.data.Dataset.range(5) 
dataset = dataset.map(lambda x: x**2) 
dataset = dataset.cache() #Caches the elements in this dataset.
# The first time reading through the data will generate the data using 
# `range` and `map`. 
list(dataset.as_numpy_iterator()) 

[0, 1, 4, 9, 16]

In [0]:
# Subsequent iterations read from the cache. 
list(dataset.as_numpy_iterator()) 

[0, 1, 4, 9, 16]

In [0]:
a = tf.data.Dataset.range(1, 4)  # ==> [ 1, 2, 3 ] 
b = tf.data.Dataset.range(4, 8)  # ==> [ 4, 5, 6, 7 ] 
ds = a.concatenate(b) # Creates a Dataset by concatenating the given dataset with this dataset.
list(ds.as_numpy_iterator())

[1, 2, 3, 4, 5, 6, 7]

In [0]:
# Slicing a 1D tensor produces scalar tensor elements. 
dataset = tf.data.Dataset.from_tensor_slices([1, 2, 3]) 
list(dataset.as_numpy_iterator()) 

[1, 2, 3]

In [0]:
# Slicing a 1D tensor produces scalar tensor elements. 
dataset = tf.data.Dataset.from_tensor_slices([1, 2, 3]) 
list(dataset.as_numpy_iterator()) 

[1, 2, 3]

In [0]:
# Slicing a tuple of 1D tensors produces tuple elements containing 
# scalar tensors. 
dataset = tf.data.Dataset.from_tensor_slices(([1, 2], [3, 4], [5, 6])) 
list(dataset.as_numpy_iterator()) 

[(1, 3, 5), (2, 4, 6)]

In [0]:
# Dictionary structure is also preserved. 
dataset = tf.data.Dataset.from_tensor_slices({"a": [1, 2], "b": [3, 4]}) 
list(dataset.as_numpy_iterator()) == [{'a': 1, 'b': 3}, 
                                      {'a': 2, 'b': 4}]

True

In [0]:
# Two tensors can be combined into one Dataset object. 
features = tf.constant([[1, 3], [2, 1], [3, 3]]) # ==> 3x2 tensor 
labels = tf.constant(['A', 'B', 'A']) # ==> 3x1 tensor 
dataset = dataset.from_tensor_slices((features, labels)) 
# Both the features and the labels tensors can be converted 
# to a Dataset object separately and combined after. 
features_dataset = dataset.from_tensor_slices(features) 
labels_dataset = dataset.from_tensor_slices(labels) 
dataset = dataset.zip((features_dataset, labels_dataset)) 
# A batched feature and label set can be converted to a Dataset 
# in similar fashion. 
batched_features = tf.constant([[[1, 3], [2, 3]], 
                                [[2, 1], [1, 2]], 
                                [[3, 3], [3, 2]]], shape=(3, 2, 2)) 
batched_labels = tf.constant([['A', 'A'], 
                              ['B', 'B'], 
                              ['A', 'B']], shape=(3, 2, 1)) 
dataset = dataset.from_tensor_slices((batched_features, batched_labels)) 
for element in dataset.as_numpy_iterator(): 
  print(element) 

(array([[1, 3],
       [2, 3]], dtype=int32), array([[b'A'],
       [b'A']], dtype=object))
(array([[2, 1],
       [1, 2]], dtype=int32), array([[b'B'],
       [b'B']], dtype=object))
(array([[3, 3],
       [3, 2]], dtype=int32), array([[b'A'],
       [b'B']], dtype=object))


In [0]:
dataset = tf.data.Dataset.from_tensor_slices([1, 2, 3]) 
dataset = dataset.enumerate(start=5) #Enumerates the elements of this dataset.
for element in dataset.as_numpy_iterator(): 
  print(element)

(5, 1)
(6, 2)
(7, 3)


In [0]:
# The nested structure of the input dataset determines the structure of 
# elements in the resulting dataset. 
dataset = tf.data.Dataset.from_tensor_slices([(7, 8), (9, 10)]) 
dataset = dataset.enumerate() 
for element in dataset.as_numpy_iterator(): 
  print(element) 

(0, array([7, 8], dtype=int32))
(1, array([ 9, 10], dtype=int32))


In [0]:
dataset = tf.data.Dataset.from_tensor_slices([1, 2, 3]) 
dataset = dataset.filter(lambda x: x < 3) 
list(dataset.as_numpy_iterator()) 

[1, 2]

In [0]:
# `tf.math.equal(x, y)` is required for equality comparison 
def filter_fn(x): 
  return tf.math.equal(x, 1) 
dataset = dataset.filter(filter_fn) 
list(dataset.as_numpy_iterator()) 

[1]

In [0]:
dataset = dataset.from_tensor_slices([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) 
dataset = dataset.flat_map(lambda x: dataset.from_tensor_slices(x)) # Use flat_map if you want to make sure that the order of your dataset stays the same. 
#For example, to flatten a dataset of batches into a dataset of their elements
list(dataset.as_numpy_iterator())

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [0]:
def gen(): 
  for i in itertools.count(1): 
    yield (i, [1] * i) 
dataset = tf.data.Dataset.from_generator(gen,  #Creates a Dataset whose elements are generated by generator.
     (tf.int64, tf.int64), 
     (tf.TensorShape([]), tf.TensorShape([None]))) 
list(dataset.take(3).as_numpy_iterator())

[(1, array([1])), (2, array([1, 1])), (3, array([1, 1, 1]))]

In [0]:
dataset = tf.data.Dataset.from_tensors([1, 2, 3]) # Creates a Dataset with a single element, comprising the given tensors.
list(dataset.as_numpy_iterator()) 

[array([1, 2, 3], dtype=int32)]

In [0]:
dataset = tf.data.Dataset.from_tensors(([1, 2, 3], 'A')) 
list(dataset.as_numpy_iterator()) 

[(array([1, 2, 3], dtype=int32), b'A')]

In [0]:
# Preprocess 4 files concurrently, and interleave blocks of 16 records 
# from each file. 
filenames = ["/var/data/file1.txt", "/var/data/file2.txt", 
             "/var/data/file3.txt", "/var/data/file4.txt"] 
dataset = tf.data.Dataset.from_tensor_slices(filenames) 
def parse_fn(filename): 
  return tf.data.Dataset.range(10) 
dataset = dataset.interleave(lambda x: 
    tf.data.TextLineDataset(x).map(parse_fn, num_parallel_calls=1), 
    cycle_length=4, block_length=16) 

In [0]:
dataset = dataset.range(1, 6)  # ==> [ 1, 2, 3, 4, 5 ] 
# NOTE: New lines indicate "block" boundaries. 
dataset = dataset.interleave( 
    lambda x: dataset.from_tensors(x).repeat(6), 
    cycle_length=2, block_length=4) 
list(dataset.as_numpy_iterator()) 
#The cycle_length and block_length arguments control the order in which elements are produced. 
#cycle_length controls the number of input elements that are processed concurrently.
#cycle_length input elements, open iterators on the returned Dataset objects, 
# and cycle through them producing block_length consecutive elements from each iterator, 

[1,
 1,
 1,
 1,
 2,
 2,
 2,
 2,
 1,
 1,
 2,
 2,
 3,
 3,
 3,
 3,
 4,
 4,
 4,
 4,
 3,
 3,
 4,
 4,
 5,
 5,
 5,
 5,
 5,
 5]

In [0]:
elements = [[1, 2], 
            [3, 4, 5], 
            [6, 7], 
            [8]] 
A = tf.data.Dataset.from_generator(lambda: iter(elements), tf.int32) 
# Pad to the smallest per-batch size that fits all elements. 
B = A.padded_batch(2, padded_shapes=[None]) 
for element in B.as_numpy_iterator(): 
  print(element) 
#Combines consecutive elements of this dataset into padded batches.
#This transformation combines multiple consecutive elements of the input dataset into a single element.

[[1 2 0]
 [3 4 5]]
[[6 7]
 [8 0]]


In [0]:
dataset = tf.data.Dataset.range(3) 
dataset = dataset.prefetch(2) 
list(dataset.as_numpy_iterator()) 

[0, 1, 2]

In [0]:
import tensorflow as tf
a = tf.add(3, 5)
print(a)

tf.Tensor(8, shape=(), dtype=int32)


In [0]:
a = tf.constant([[3, 5], [4, 8]])
b = tf.constant([[1, 6], [2, 9]])
tf.math.add_n([a, b, a])  # [[7, 16], [10, 25]]

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 7, 16],
       [10, 25]], dtype=int32)>

In [0]:
# Launch the graph in a session.
with tf.compat.v1.Session() as ses:
     # Build a graph.
     a = tf.constant(5.0)
     b = tf.constant(6.0)
     c = tf.add(a, b)
     # Evaluate the tensor `c`.
     print(ses.run(c))
# Using the `close()` method.
ses.close()

11.0


In [0]:
x = 2
y = 3
op1 = tf.add(x, y)
op2 = tf.multiply(x, y)
op3 = tf.pow(op2, op1)
with tf.compat.v1.Session() as sess:
    op3 = sess.run(op3)
print(op3)

AttributeError: ignored

In [0]:
# Launch the graph in a session.
with tf.compat.v1.Session() as ses:
     # Build a graph.
      x = 2
      y = 3
      add_op = tf.add(x, y)
      mul_op = tf.multiply(x, y)
      useless = tf.multiply(x, add_op)
      pow_op = tf.pow(add_op, mul_op)
      # Evaluate the tensor `c`.
      print(ses.run(pow_op))
# Using the `close()` method.
ses.close()

15625


In [0]:
# Creates a graph.
physical_devices = tf.config.list_physical_devices('GPU') 
try: 
  tf.config.experimental.set_memory_growth(physical_devices[0], True) 
except: 
  # Invalid device or cannot modify virtual devices once initialized. 
  pass 
  a = tf.constant([1.0, 2.0, 3.0, 4.0, 5.0, 6.0], name='a')
  b = tf.constant([1.0, 2.0, 3.0, 4.0, 5.0, 6.0], name='b')
  c = tf.multiply(a, b)
# Creates a session with log_device_placement set to True.
#sess = tf.compat.v1.Session(config=tf.config.experimental(log_device_placement=True))
# Runs the op.
print(c)


tf.Tensor([ 1.  4.  9. 16. 25. 36.], shape=(6,), dtype=float32)


In [0]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
